### ISSUE TITLE
Community Forum seems to be down

### ISSUE THREAD

**Issue by Erudition** [villagekit/gridbeam.xyz#14]
Getting a 502 error when trying to visit
https://discuss.villagekit.com/

Has the community moved somewhere else? Hope it's not abandoned! Excited to participate

**Comment by ahdinosaur** [comment]
Hi @Erudition, thanks for reaching out to let us know. :blush: 

Should be fixed now, sorry about that. I recently upgraded Discourse, so something must have gone awry. :shrug: 

Def not abandoned, happy for you to join us, welcome! :purple_heart:
