### ISSUE TITLE
Epub / PDF excerpts & table of contents links not working 

### ISSUE THREAD

**Issue by jonathandann** [villagekit/gridbeam.xyz#17]
Looks like those links are pointing to the w wrong AWS buckets.

thanks.

**Comment by ahdinosaur** [comment]
hi @jonathandann, i assume you mean the links on https://newsociety.com for the "How to Build With Grid Beam" book. i'm neither the author nor publisher of the book, so i don't think i can help, sorry. but i do have a [~~pirate copy~~ :pirate_flag:](https://www.ocf.berkeley.edu/~mwilliams/reading/construction/How-to-Build-With-Grid-Beam.pdf), buy the book if you like. :seedling:
