### ISSUE TITLE
Beam width mismatch with bolt diameters

### ISSUE THREAD

**Issue by christianbundy** [villagekit/gridbeam.xyz#4]
Hi @ahdinosaur! I think I found a mismatch between the beam width and bolt diameters. Maybe?

The third item in each list:

- **Beam width:** 1 1⁄2 inch | 40 mm
- **Bolt diameter:** 3⁄8 inch | 9.5 mm

But gridbeam.com [webpage](http://gridbeam.com/woodproducts.html), which uses 1.5 inch beam width, says:

> The holes are 5/16 inch diameter and designed to accept our joint connector bolt and nut.

What's the "correct" bolt diameter for a beam width of 1.5 inches?

Thanks a bunch! I've been loving gridbeam.

---

Wait nvm, just saw you posted a message on SSB! I'll read that now.

**Comment by christianbundy** [comment]
Maybe this would be better phrased as a question: do beam widths correspond to bolt diameters? If so, should the `n`th item in one list correspond to the `n`th item in the other list? After reading your post on SSB (and *How To Build Your Own Living Structures*) it sounds like 1.5" beam diameters match up with a 1/4" bolt diameter.

**Comment by ahdinosaur** [comment]
hi @christianbundy, yes thanks for the bug report. i've been meaning to fix this, as i got confused in the exact same way a few weeks ago! :bug:
